### ISSUE TITLE
Feature: User can 

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for cards
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
![Search Modal](https://user-images.githubusercontent.com/16251746/127089786-4883d7ae-2354-4cec-aba8-748dce254bef.png)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Make the basic web page needed to do the search function.
- [ ] Add input event handler for search box
- [ ] Make a dataview for the modal shown in mockup
- [ ] On input type. show modal
- [ ] Create an array var called searchQueries and populate it with mock data
- [ ] Within modal, create a carousel with three images that pans through dummy data.
- [ ] Create an xmlhttp object that sets searchQueries to it's response
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
