### ISSUE TITLE
Feature: User can switch between saved decks.

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/ajax-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can switch between saved decks.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can switch between decks by clicking on decks.

## 🖼️ Wireframes
![Mobile Deck View](https://user-images.githubusercontent.com/16251746/127721935-9ef80010-656b-4303-b5aa-2f929c56e6cb.png)
![Desktop Search](https://user-images.githubusercontent.com/16251746/127721944-1aebd9fb-0c35-4535-be99-c6453acc52a6.png)
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Save deck strings to local storage
- [x] Save data.deckids to local storage
- [x] In the on window load event handler, get deckids array in local storage, then loop through the id keys in local storage,  convert them to decks with Deck.loadFromString(), and push the return to data.decks.
- [x] Create a data view for listing decks on mobile
- [x] Create a tab data view that looks like the wireframe
- [x] Add a click event handler to the button in the header to open the tab data view
- [x] in the tab data view, add a button to the decks text to open the decks data view
- [x] hide the button on desktop
- [x] Create a mockup in html for a deck for both mobile and desktop
- [x] Create a function that creates a DOM tree for html
- [x] Create a function that create a DOM tree for mobile
- [x] Loop through all decks in data.decks, and append them to the DOM with attribute data-id equal to their ids
- [x] Modify Deck.setActiveDeck to take ids
- [x] Add a click event handler at the end of both DOM tree rendering functions that calls Deck.setActiveDeck()
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
