### ISSUE TITLE
Feature: User can search for Magic: The Gathering Cards

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User Can search for Magic: The Gathering Cards
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will click on the search bar, and will see a carousel of cards based on their search query.
## 🖼️ Wireframes
![Search Modal](https://user-images.githubusercontent.com/16251746/127077780-550564aa-4ce3-437f-8174-0923f475a201.png)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the Mobile HTML for an empty deck.
- [x] Create the desktop HTML for an empty deck.
- [x] Make sure both versions match the wireframe.
- [x] Create the HTML for mobile modal search view
- [x] Create the HTML for desktop modal search view
- [x] Allow user to search for cards, add xhr results to array for use later.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
