### ISSUE TITLE
Feature: User can view their cards in a list .

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their cards in a list.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will want to be able to see the cards that they chose in the search carousel.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Mobile List View](https://user-images.githubusercontent.com/16251746/127546692-ca9179d2-272f-446b-8826-bad05535549c.png)
![Desktop Main](https://user-images.githubusercontent.com/16251746/127546754-cac6dffc-9b9d-4c8a-9fce-c723ead9b719.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create a mockup of a list item card in the HTML file.
- [x] Create a function for creating list items for cards that match the wireframe.
- [x] Add event listener to each item that listens for it's button icons
- [x] Call the removeCard or addCard  function from MajaxCard.
- [x] Create a mockup of a card group for mobile in the HTML file.
- [x] Create a function that generates card groups.
- [x] Add a hover event listener to the card group, and show the deletion/creation view on the topmost card in a stack
- [x] Call the removeCard or addCard function from MajaxCard.
- [x] Update MajaxCard class methods removeCard and addCard to update the items in the HTML.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Make sure that the UX/UI matches the wireframe.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
