### ISSUE TITLE
Bug:  Double faced cards cannot be displayed in searches.

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/ajax-project#7]
#### Desired Behavior

> ##### The app should ...

App should be able to display double faced cards.
#### Actual Behavior

> ##### The app does this instead ...
Strange card types return Null for their images, because they store their URIS in two faces.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Search a query with a double face.
## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] Add the front face of a card to its data-front attribute on load if it is a double faced card.
- [ ] Add the back to its data-back
- [ ] Add functionality that allows you to 'flip' an image
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
